#!/usr/bin/env python3
"""Deterministic seeded draw of the n=16 extension sample (PREREGISTRATION_V1.md Amendment 6).

Parses the INCLUDED candidate frame (section 2b) from
EXTENSION_FRAME_ENUMERATION_NOTES.md -- the single committed source of truth,
each row traced to a retrieved DEFM14A accession -- deduplicates to the deal,
excludes any anchor-tier overlap, sorts by the frame's own section-2b index, and
runs a seeded (20260520) Mersenne-Twister permutation. The first 16 rows of the
permutation are the extension sample; the remainder is the ordered replacement
queue used when a drawn case fails per-deal verification at dossier-build
(terminated / < $1bn / foreign registrant / anchor overlap), per Amendment 6.

Reproducibility (PAQS 37a-e):
  - Deterministic given the committed notes file: seed 20260520, Python
    random.Random (MT19937). Re-running yields byte-identical output.
  - Run (from repo root):
        uv run python code/draw_extension_sample.py
  - Dependencies: Python 3.12 standard library only.
  - Writes: extension_frame_2001_2020.csv (the parsed, deduplicated frame) and
    EXTENSION_SAMPLE_n16.md (the drawn sample + replacement queue). Both are
    deterministic projections of the committed notes file.
"""

from __future__ import annotations

import csv
import random
from pathlib import Path

HERE = Path(__file__).resolve().parent
NOTES = HERE / "EXTENSION_FRAME_ENUMERATION_NOTES.md"
FRAME_CSV = HERE / "extension_frame_2001_2020.csv"
SAMPLE_MD = HERE / "EXTENSION_SAMPLE_n16.md"

SEED = 20260520
N_DRAW = 16

# Anchor-tier company names (Amendment 6 anchor-overlap exclusion). Conservative
# substring match against target + acquirer (lower-cased).
ANCHOR_TERMS = [
    "daimler",
    "chrysler",
    "lehman",
    "3com",
    "palm",
    "friendfeed",
    "service corporation",
    "funeral",
    "at&t",
    "lucent",
    "mcdonald",
    "netflix",
    "medtronic",
    "covidien",
    "nyse",
    "archipelago",
    "toyota",
    "nummi",
    "novartis",
    "glaxo",
    "gsk",
    "elbulli",
]


def parse_included_frame() -> list[dict]:
    """Extract the section-2b INCLUDED table rows from the notes file."""
    text = NOTES.read_text(encoding="utf-8").splitlines()
    rows: list[dict] = []
    in_2b = False
    for line in text:
        if line.strip().startswith("### 2b"):
            in_2b = True
            continue
        if in_2b and line.strip().startswith("### 2c"):
            break
        if not in_2b:
            continue
        if not line.lstrip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 8:
            continue
        if not cells[0].isdigit():  # skip header and separator rows
            continue
        rows.append(
            {
                "idx": int(cells[0]),
                "target": cells[1],
                "acquirer": cells[2],
                "year": cells[3],
                "target_cik": cells[4],
                "defm14a_accession": cells[5],
                "reported_value": cells[6],
                "value_evidenced": cells[7],
            }
        )
    return rows


def dedup_and_filter(rows: list[dict]) -> tuple[list[dict], list[dict]]:
    """Drop within-table duplicates and anchor-overlap rows; return (kept, dropped)."""
    kept, dropped = [], []
    for r in rows:
        blob = f"{r['target']} {r['acquirer']}".lower()
        if "duplicate" in r["value_evidenced"].lower():
            r["_drop_reason"] = "dedup (marked DUPLICATE)"
            dropped.append(r)
        elif any(term in blob for term in ANCHOR_TERMS):
            r["_drop_reason"] = "anchor-overlap"
            dropped.append(r)
        else:
            kept.append(r)
    return kept, dropped


def main() -> int:
    rows = parse_included_frame()
    kept, dropped = dedup_and_filter(rows)
    frame = sorted(kept, key=lambda r: r["idx"])

    # Write the parsed, deduplicated frame as a machine-readable artifact.
    with FRAME_CSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(
            fh,
            fieldnames=[
                "idx",
                "target",
                "acquirer",
                "year",
                "target_cik",
                "defm14a_accession",
                "reported_value",
                "value_evidenced",
            ],
        )
        w.writeheader()
        for r in frame:
            w.writerow({k: r[k] for k in w.fieldnames})

    # Seeded permutation: first N_DRAW = sample; rest = ordered replacement queue.
    perm = list(frame)
    random.Random(SEED).shuffle(perm)
    sample = perm[:N_DRAW]
    replacement_queue = perm[N_DRAW:]

    lines = [
        "# Extension sample (n=16) — seeded draw",
        "",
        "> GENERATED by `draw_extension_sample.py` from the committed",
        "> `EXTENSION_FRAME_ENUMERATION_NOTES.md` section-2b frame, per",
        "> PREREGISTRATION_V1.md Amendment 6. Deterministic: seed"
        f" {SEED} (Python random.Random / MT19937). Do not hand-edit; re-run the",
        "> script to regenerate.",
        "",
        f"- Parsed section-2b INCLUDED rows: {len(rows)}",
        f"- Dropped (dedup + anchor-overlap): {len(dropped)}",
        f"- Final frame size: {len(frame)}",
        f"- Draw: first {N_DRAW} of the seeded permutation.",
        "- Per-deal >= $1bn value and deal-completion are confirmed at",
        "  dossier-build; a failing case is replaced by the next row of the",
        "  replacement queue below, in order.",
        "",
        "## Drawn extension sample (build dossiers E01-E16 for these)",
        "",
        "| # | Target | Acquirer | Year | Target CIK | DEFM14A accession |",
        "|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(sample, 1):
        lines.append(
            f"| E{i:02d} | {r['target']} | {r['acquirer']} | {r['year']} "
            f"| {r['target_cik']} | {r['defm14a_accession']} |"
        )
    lines += [
        "",
        "## Ordered replacement queue (use in order if a drawn case fails verification)",
        "",
        "| pos | Target | Acquirer | Year | Target CIK | DEFM14A accession |",
        "|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(replacement_queue, 1):
        lines.append(
            f"| R{i:02d} | {r['target']} | {r['acquirer']} | {r['year']} "
            f"| {r['target_cik']} | {r['defm14a_accession']} |"
        )
    lines += [
        "",
        "## Dropped rows (transparency)",
        "",
        "| Target | Acquirer | Reason |",
        "|---|---|---|",
    ]
    for r in dropped:
        lines.append(f"| {r['target']} | {r['acquirer']} | {r['_drop_reason']} |")
    lines.append("")
    SAMPLE_MD.write_text("\n".join(lines), encoding="utf-8")

    print(
        f"Parsed {len(rows)} INCLUDED rows; dropped {len(dropped)}; frame {len(frame)}."
    )
    print(
        f"Drew {len(sample)} (seed {SEED}); replacement queue {len(replacement_queue)}."
    )
    print(f"Wrote {FRAME_CSV.name} and {SAMPLE_MD.name}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
